import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        "on-surface": "#221a0d",
        "inverse-on-surface": "#feefd8",
        outline: "#8a7268",
        "on-primary-container": "#fffbff",
        "on-primary-fixed": "#351000",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-container-low": "#fff2e0",
        "on-primary-fixed-variant": "#7c2e00",
        "surface-container-high": "#f6e6d0",
        "on-secondary-container": "#715300",
        "primary-container": "#bd5621",
        background: "#fff8f3",
        "on-tertiary-fixed-variant": "#0e5138",
        "surface-container": "#fcecd6",
        "surface-tint": "#9f410a",
        "tertiary-container": "#448064",
        "secondary-container": "#ffc641",
        "border-tan": "#E8E0D4",
        "background-sand": "#FAF7F2",
        "surface-variant": "#f0e0cb",
        "primary-fixed-dim": "#ffb595",
        "status-warning": "#E67E22",
        "surface-white": "#FFFFFF",
        "on-primary": "#ffffff",
        "surface-bright": "#fff8f3",
        primary: "#9c3f07",
        tertiary: "#2a674c",
        "tertiary-fixed": "#b1f0ce",
        secondary: "#795900",
        "secondary-fixed": "#ffdfa0",
        "tertiary-fixed-dim": "#95d4b3",
        "on-tertiary-fixed": "#002114",
        "surface-dim": "#e7d8c2",
        "inverse-surface": "#382f20",
        "secondary-fixed-dim": "#f6be39",
        "outline-variant": "#ddc1b5",
        "on-error-container": "#93000a",
        "surface-container-highest": "#f0e0cb",
        "on-secondary-fixed": "#261a00",
        "on-surface-variant": "#56423a",
        "on-tertiary-container": "#f5fff7",
        "status-error": "#C0392B",
        surface: "#fff8f3",
        "error-container": "#ffdad6",
        error: "#ba1a1a",
        "primary-fixed": "#ffdbcc",
        "on-secondary-fixed-variant": "#5c4300",
        "on-background": "#221a0d",
        "clay-heading": "#8B4513",
        "on-tertiary": "#ffffff",
        "inverse-primary": "#ffb595",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        md: "16px",
        xl: "32px",
        sm: "8px",
        "margin-mobile": "16px",
        "container-max": "1200px",
        lg: "24px",
        "margin-desktop": "32px",
        xs: "4px",
        gutter: "16px",
      },
      fontFamily: {
        "headline-sm": ["var(--font-epilogue)", "sans-serif"],
        "body-sm": ["var(--font-plus-jakarta)", "sans-serif"],
        "body-lg": ["var(--font-plus-jakarta)", "sans-serif"],
        "label-caps": ["var(--font-jetbrains)", "monospace"],
        "display-mobile": ["var(--font-epilogue)", "sans-serif"],
        "headline-md": ["var(--font-epilogue)", "sans-serif"],
        display: ["var(--font-epilogue)", "sans-serif"],
        "headline-lg": ["var(--font-epilogue)", "sans-serif"],
      },
      fontSize: {
        "headline-sm": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "body-lg": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.5px", fontWeight: "500" }],
        "display-mobile": ["30px", { lineHeight: "38px", letterSpacing: "-1px", fontWeight: "800" }],
        "headline-md": ["22px", { lineHeight: "30px", letterSpacing: "-0.5px", fontWeight: "600" }],
        display: ["36px", { lineHeight: "44px", letterSpacing: "-1.5px", fontWeight: "800" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-1px", fontWeight: "700" }],
      },
      maxWidth: {
        "container-max": "1200px",
      },
      boxShadow: {
        card: "0 4px 6px -1px rgba(44, 36, 22, 0.06), 0 2px 4px -1px rgba(44, 36, 22, 0.04)",
        elevated: "0 12px 24px -10px rgba(44, 36, 22, 0.15)",
      },
    },
  },
  plugins: [],
};

export default config;
